language: python

python:
  - "3.5"
  - "3.4"
  - "3.3"

install:
  - pip install -r requirements.txt

script:
  - ./lint.sh
  - py.test --cov=django_crud tests
  - python setup.py check

after_success:
  - codecov
